export default [
    {
        id: 1,
        title: "Balian Beach, Indonesia",
        description: "4,254 kilometers away",
        dates: "Jan 21-26",
        price: "34,887",
        ratings: 4.86,
        img: ["1-1.webp","1-2.webp","1-3.webp",],
    },
    {
        id: 2,
        title: "Sidemen, Indonesia",
        description: "4,301 kilometers away",
        dates: "Feb 2-7",
        price: "129,377",
        ratings: 4.84,
        img: ["2-1.webp","2-2.webp","2-3.webp",],
    },
    {
        id: 3,
        title: "Phang Nga, Thailand",
        description: "2,035 kilometers away",
        dates: "Jan 4-9",
        price: "160,657",
        img: ["3-1.webp","3-2.webp","3-3.webp",],
    },
    {
        id: 4,
        title: "Abiansemal, Indonesia",
        description: "4,282 kilometers away",
        dates: "Mar 9-14",
        price: "161,635",
        ratings: 4.84,
        img: ["4-1.webp","4-2.webp","4-3.webp",],
    },
    {
        id: 5,
        title: "Bophut, Thailand",
        description: "2,244 kilometers away",
        dates: "Jan 11-16",
        price: "317,472",
        ratings: 5.0,
        img: ["5-1.webp","5-2.webp","5-3.webp",],
    },
    {
        id: 6,
        title: "Koh Samui, Thailand",
        description: "2,240 kilometers away",
        dates: "Feb 19-24",
        price: "676,989",
        img: ["6-1.webp","6-2.webp","6-3.webp",],
    },
    {
        id: 7,
        title: "Seririt, Indonesia",
        description: "4,242 kilometers away",
        dates: "Mar 7-12",
        price: "44,690",
        ratings: 4.8,
        img: ["7-1.webp","7-2.webp","7-3.webp",],
    },
    {
        id: 8,
        title: "Phang Nga, Thailand",
        description: "2,035 kilometers away",
        dates: "Jan 1-6",
        price: "333,585",
        img: ["8-1.webp","8-2.webp","8-3.webp",],
    },
    {
        id: 9,
        title: "Pererenan, Thailand",
        description: "4,277 kilometers away",
        dates: "Jan 3-8",
        price: "214,758",
        img: ["9-1.webp","9-2.webp","9-3.webp",],
    },
    {
        id: 10,
        title: "Phang Nga, Thailand",
        description: "2,035 kilometers away",
        dates: "Jan 21-26",
        price: "375,301",
        img: ["10-1.webp","10-2.webp","10-3.webp",],
    },
    
]